/*
 * mw/version.h — Generated by CMake. DO NOT EDIT.
 *
 * Single-source version information for linux-middleware.
 * All version constants in the platform originate here.
 *
 * Include via:  #include "mw/version.h"
 */

#ifndef MW_VERSION_H
#define MW_VERSION_H

/* Semantic version components */
#define MW_VERSION_MAJOR   2
#define MW_VERSION_MINOR   1
#define MW_VERSION_PATCH   0
#define MW_VERSION_TWEAK   0

/* Full version string */
#define MW_VERSION_STRING  "2.1.0"

/* Packed integer: 0xMMMMmmmmPPPPTTTT — use for fast numeric comparison */
#define MW_VERSION_INT     ((MW_VERSION_MAJOR << 24) | \
                            (MW_VERSION_MINOR << 16) | \
                            (MW_VERSION_PATCH <<  8) | \
                             MW_VERSION_TWEAK)

/* Minimum version check macro */
#define MW_VERSION_AT_LEAST(maj, min, pat) \
    (MW_VERSION_INT >= (((maj) << 24) | ((min) << 16) | ((pat) << 8)))

/* Build metadata */
#define MW_BUILD_TYPE      "RelWithDebInfo"
#define MW_BUILD_TIMESTAMP ""
#define MW_C_COMPILER      "GNU 15.2.1"
#define MW_CXX_COMPILER    "GNU 15.2.1"

/* Tuning constants — set via CMake options, single source of truth */
#define SM_MAX_SERVICES    32
#define HAL_REGISTRY_SIZE  128

/* Security feature flags — compiled-in, not runtime-toggleable */
#define MW_SECURITY_SANDBOX_ENABLED    
#define MW_SECURITY_SECCOMP_ENABLED    
#define MW_SECURITY_CAPS_ENABLED       
#define MW_SECURITY_VERIFY_ENABLED     

#endif /* MW_VERSION_H */
