# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "3.0.0")
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 3.0.0...4.0)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS mw::mw_sm_lib mw::mw_sm_infrastructure mw::mw_sm_security mw::mw_sm_lifecycle mw::mw_sm_observability mw::mw_sm_enterprise mw::mw_core mw::mw_hal mw::mw_hal_iface mw::mw_hal_audio mw::mw_hal_camera mw::mw_hal_gpio mw::mw_hal_sensors mw::mw_sec_capabilities mw::mw_sec_sandbox mw::mw_sec_seccomp mw::mw_sec_verify mw::mw_sec_manager mw::mw_svc_common mw::mw_proxy mw::mw_proxy_c mw::mw_mon_collectors mw::mw_mon_metrics mw::mw_mon_health mw::mw_mon_alerts mw::mw_mon_tracing mw::mw_compile_opts mw::mw_version_hdr mw::mw_platform_checks)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target mw::mw_sm_lib
add_library(mw::mw_sm_lib INTERFACE IMPORTED)

set_target_properties(mw::mw_sm_lib PROPERTIES
  INTERFACE_LINK_LIBRARIES "mw::mw_sm_infrastructure;mw::mw_sm_security;mw::mw_sm_lifecycle;mw::mw_sm_observability;mw::mw_sm_enterprise;mw::mw_core"
)

# Create imported target mw::mw_sm_infrastructure
add_library(mw::mw_sm_infrastructure STATIC IMPORTED)

set_target_properties(mw::mw_sm_infrastructure PROPERTIES
  INTERFACE_LINK_LIBRARIES "mw::mw_compile_opts;mw::mw_core;mw::mw_sm_security;OpenSSL::Crypto;Threads::Threads"
)

# Create imported target mw::mw_sm_security
add_library(mw::mw_sm_security STATIC IMPORTED)

set_target_properties(mw::mw_sm_security PROPERTIES
  INTERFACE_LINK_LIBRARIES "mw::mw_compile_opts;mw::mw_core;mw::mw_sm_observability;OpenSSL::Crypto"
)

# Create imported target mw::mw_sm_lifecycle
add_library(mw::mw_sm_lifecycle STATIC IMPORTED)

set_target_properties(mw::mw_sm_lifecycle PROPERTIES
  INTERFACE_LINK_LIBRARIES "mw::mw_compile_opts;mw::mw_sm_infrastructure;mw::mw_sm_security"
)

# Create imported target mw::mw_sm_observability
add_library(mw::mw_sm_observability STATIC IMPORTED)

set_target_properties(mw::mw_sm_observability PROPERTIES
  INTERFACE_LINK_LIBRARIES "mw::mw_compile_opts;mw::mw_sm_infrastructure;mw::mw_sm_lifecycle"
)

# Create imported target mw::mw_sm_enterprise
add_library(mw::mw_sm_enterprise STATIC IMPORTED)

set_target_properties(mw::mw_sm_enterprise PROPERTIES
  INTERFACE_LINK_LIBRARIES "mw::mw_compile_opts;mw::mw_sm_lifecycle;mw::mw_sm_observability;OpenSSL::SSL;OpenSSL::Crypto;Threads::Threads"
)

# Create imported target mw::mw_core
add_library(mw::mw_core STATIC IMPORTED)

set_target_properties(mw::mw_core PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mw/core"
  INTERFACE_LINK_LIBRARIES "Threads::Threads;LibUring::LibUring;mw::mw_compile_opts;mw::mw_platform_checks;mw::mw_version_hdr"
)

if(NOT CMAKE_VERSION VERSION_LESS "3.23.0")
  target_sources(mw::mw_core
    INTERFACE
      FILE_SET "HEADERS"
      TYPE "HEADERS"
      BASE_DIRS "${_IMPORT_PREFIX}/include/mw/core"
      FILES "${_IMPORT_PREFIX}/include/mw/core/io_uring_loop.h" "${_IMPORT_PREFIX}/include/mw/core/memory_pool.h" "${_IMPORT_PREFIX}/include/mw/core/ring_buffer.h"
  )
else()
  set_property(TARGET mw::mw_core
    APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES
      "${_IMPORT_PREFIX}/include/mw/core"
  )
endif()

# Create imported target mw::mw_hal
add_library(mw::mw_hal INTERFACE IMPORTED)

set_target_properties(mw::mw_hal PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mw/hal"
  INTERFACE_LINK_LIBRARIES "mw::mw_hal_iface;mw::mw_core;\$<\$<BOOL:ON>:;mw::hal_audio>;\$<\$<BOOL:ON>:;mw::hal_camera>;\$<\$<BOOL:ON>:;mw::hal_gpio>;\$<\$<BOOL:ON>:;mw::hal_sensors>"
)

# Create imported target mw::mw_hal_iface
add_library(mw::mw_hal_iface STATIC IMPORTED)

set_target_properties(mw::mw_hal_iface PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mw/hal"
  INTERFACE_LINK_LIBRARIES "mw::mw_compile_opts;mw::mw_version_hdr;Threads::Threads"
)

if(NOT CMAKE_VERSION VERSION_LESS "3.23.0")
  target_sources(mw::mw_hal_iface
    INTERFACE
      FILE_SET "HEADERS"
      TYPE "HEADERS"
      BASE_DIRS "${_IMPORT_PREFIX}/include/mw/hal"
      FILES "${_IMPORT_PREFIX}/include/mw/hal/hal_interface.h"
  )
else()
  set_property(TARGET mw::mw_hal_iface
    APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES
      "${_IMPORT_PREFIX}/include/mw/hal"
  )
endif()

# Create imported target mw::mw_hal_audio
add_library(mw::mw_hal_audio STATIC IMPORTED)

set_target_properties(mw::mw_hal_audio PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "MW_HAL_AUDIO=1"
  INTERFACE_LINK_LIBRARIES "mw::mw_hal_iface;mw::mw_compile_opts;mw::mw_core;ALSA::ALSA"
)

# Create imported target mw::mw_hal_camera
add_library(mw::mw_hal_camera STATIC IMPORTED)

set_target_properties(mw::mw_hal_camera PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "MW_HAL_CAMERA=1"
  INTERFACE_LINK_LIBRARIES "mw::mw_hal_iface;mw::mw_compile_opts;mw::mw_core"
)

# Create imported target mw::mw_hal_gpio
add_library(mw::mw_hal_gpio STATIC IMPORTED)

set_target_properties(mw::mw_hal_gpio PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "MW_HAL_GPIO=1"
  INTERFACE_LINK_LIBRARIES "mw::mw_hal_iface;mw::mw_compile_opts;mw::mw_core"
)

# Create imported target mw::mw_hal_sensors
add_library(mw::mw_hal_sensors STATIC IMPORTED)

set_target_properties(mw::mw_hal_sensors PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "MW_HAL_SENSORS=1"
  INTERFACE_LINK_LIBRARIES "mw::mw_hal_iface;mw::mw_compile_opts;mw::mw_core"
)

# Create imported target mw::mw_sec_capabilities
add_library(mw::mw_sec_capabilities STATIC IMPORTED)

set_target_properties(mw::mw_sec_capabilities PROPERTIES
  INTERFACE_LINK_LIBRARIES "mw::mw_compile_opts;LibCap::LibCap;mw::mw_core"
)

# Create imported target mw::mw_sec_sandbox
add_library(mw::mw_sec_sandbox STATIC IMPORTED)

set_target_properties(mw::mw_sec_sandbox PROPERTIES
  INTERFACE_LINK_LIBRARIES "mw::mw_compile_opts;mw::mw_core"
)

# Create imported target mw::mw_sec_seccomp
add_library(mw::mw_sec_seccomp STATIC IMPORTED)

set_target_properties(mw::mw_sec_seccomp PROPERTIES
  INTERFACE_LINK_LIBRARIES "mw::mw_compile_opts;LibSeccomp::LibSeccomp;mw::mw_core"
)

# Create imported target mw::mw_sec_verify
add_library(mw::mw_sec_verify STATIC IMPORTED)

set_target_properties(mw::mw_sec_verify PROPERTIES
  INTERFACE_LINK_LIBRARIES "mw::mw_compile_opts;OpenSSL::Crypto;mw::mw_core;mw::mw_sm_lib"
)

# Create imported target mw::mw_sec_manager
add_library(mw::mw_sec_manager STATIC IMPORTED)

set_target_properties(mw::mw_sec_manager PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mw/security"
  INTERFACE_LINK_LIBRARIES "mw::mw_sec_capabilities;mw::mw_sec_sandbox;mw::mw_sec_seccomp;mw::mw_sec_verify;mw::mw_compile_opts"
)

# Create imported target mw::mw_svc_common
add_library(mw::mw_svc_common STATIC IMPORTED)

set_target_properties(mw::mw_svc_common PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mw/services"
  INTERFACE_LINK_LIBRARIES "mw::mw_sm_lib;mw::mw_core;mw::mw_compile_opts;mw::mw_version_hdr;Threads::Threads"
)

if(NOT CMAKE_VERSION VERSION_LESS "3.23.0")
  target_sources(mw::mw_svc_common
    INTERFACE
      FILE_SET "HEADERS"
      TYPE "HEADERS"
      BASE_DIRS "${_IMPORT_PREFIX}/include/mw/services"
      FILES "${_IMPORT_PREFIX}/include/mw/services/service_base.h" "${_IMPORT_PREFIX}/include/mw/services/service_config.h" "${_IMPORT_PREFIX}/include/mw/services/service_ipc.h"
  )
else()
  set_property(TARGET mw::mw_svc_common
    APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES
      "${_IMPORT_PREFIX}/include/mw/services"
  )
endif()

# Create imported target mw::mw_proxy
add_library(mw::mw_proxy SHARED IMPORTED)

set_target_properties(mw::mw_proxy PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mw/proxy"
)

# Create imported target mw::mw_proxy_c
add_library(mw::mw_proxy_c SHARED IMPORTED)

set_target_properties(mw::mw_proxy_c PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mw/proxy"
  INTERFACE_LINK_LIBRARIES "mw::mw_compile_opts"
)

# Create imported target mw::mw_mon_collectors
add_library(mw::mw_mon_collectors STATIC IMPORTED)

set_target_properties(mw::mw_mon_collectors PROPERTIES
  INTERFACE_LINK_LIBRARIES "mw::mw_compile_opts;mw::mw_mon_metrics;mw::mw_mon_health;mw::mw_core;mw::mw_hal_iface;Threads::Threads"
)

# Create imported target mw::mw_mon_metrics
add_library(mw::mw_mon_metrics STATIC IMPORTED)

set_target_properties(mw::mw_mon_metrics PROPERTIES
  INTERFACE_LINK_LIBRARIES "mw::mw_compile_opts;mw::mw_core;Threads::Threads"
)

# Create imported target mw::mw_mon_health
add_library(mw::mw_mon_health STATIC IMPORTED)

set_target_properties(mw::mw_mon_health PROPERTIES
  INTERFACE_LINK_LIBRARIES "mw::mw_compile_opts;mw::mw_mon_metrics;mw::mw_core"
)

# Create imported target mw::mw_mon_alerts
add_library(mw::mw_mon_alerts STATIC IMPORTED)

set_target_properties(mw::mw_mon_alerts PROPERTIES
  INTERFACE_LINK_LIBRARIES "mw::mw_compile_opts;mw::mw_mon_metrics;mw::mw_mon_health;mw::mw_core"
)

# Create imported target mw::mw_mon_tracing
add_library(mw::mw_mon_tracing STATIC IMPORTED)

set_target_properties(mw::mw_mon_tracing PROPERTIES
  INTERFACE_LINK_LIBRARIES "mw::mw_compile_opts;mw::mw_core"
)

# Create imported target mw::mw_compile_opts
add_library(mw::mw_compile_opts INTERFACE IMPORTED)

set_target_properties(mw::mw_compile_opts PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "_POSIX_C_SOURCE=200809L;_GNU_SOURCE;SM_MAX_SERVICES_BUILD=32;HAL_REGISTRY_SIZE=128;POOL_DEFAULT_BLOCKS=8;\$<\$<BOOL:ON>:MW_SANDBOX_ENABLED=1>;\$<\$<BOOL:ON>:MW_SECCOMP_ENABLED=1>;\$<\$<BOOL:ON>:MW_CAPS_ENABLED=1>;\$<\$<BOOL:ON>:MW_VERIFY_ENABLED=1>;\$<\$<BOOL:OFF>:MW_URING_SQPOLL=1>"
  INTERFACE_COMPILE_OPTIONS "\$<\$<COMPILE_LANGUAGE:C>:-fstack-protector-strong;-fstack-clash-protection;-fcf-protection=full;-D_FORTIFY_SOURCE=3;-ftrivial-auto-var-init=zero;-Wformat=2;-Wformat-security;-Wformat-overflow=2;-Warray-bounds=2;-Wstringop-overflow=4;-Wstringop-truncation;-fno-strict-overflow;-fwrapv;-fno-delete-null-pointer-checks;-Wimplicit-function-declaration;-Wimplicit-int;-Wstrict-prototypes;-Wmissing-prototypes;-Wall;-Wextra;-Wshadow;-Wpointer-arith;-Wcast-align;-Wwrite-strings;-Wnull-dereference;-Wdouble-promotion;-Wundef>;\$<\$<COMPILE_LANGUAGE:CXX>:-fstack-protector-strong;-fstack-clash-protection;-fcf-protection=full;-D_FORTIFY_SOURCE=3;-ftrivial-auto-var-init=zero;-Wformat=2;-Wformat-security;-Wformat-overflow=2;-Warray-bounds=2;-Wstringop-overflow=4;-Wstringop-truncation;-fno-strict-overflow;-fwrapv;-fno-delete-null-pointer-checks;-Wall;-Wextra;-Wshadow;-Wnon-virtual-dtor;-Wold-style-cast;-Wcast-align;-Wnull-dereference;-Woverloaded-virtual;-Wdouble-promotion;-Wundef>"
  INTERFACE_LINK_OPTIONS "-Wl,-z,relro;-Wl,-z,now;-Wl,-z,noexecstack;-Wl,-z,notext;-Wl,-z,defs;-Wl,-z,separate-code"
)

# Create imported target mw::mw_version_hdr
add_library(mw::mw_version_hdr INTERFACE IMPORTED)

set_target_properties(mw::mw_version_hdr PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target mw::mw_platform_checks
add_library(mw::mw_platform_checks INTERFACE IMPORTED)

set_target_properties(mw::mw_platform_checks PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "_GNU_SOURCE;\$<\$<BOOL:1>:;MW_HAVE_EXPLICIT_BZERO=1>;\$<\$<BOOL:1>:;MW_HAVE_MEMFD_CREATE=1>;\$<\$<BOOL:1>:;MW_HAVE_GETRANDOM=1>;\$<\$<BOOL:1>:;MW_HAVE_IIO=1>;\$<\$<BOOL:>:;MW_HAVE_V4L2=1>;MW_CACHE_LINE_SIZE=64"
)

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/linux_middlewareTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  if(CMAKE_VERSION VERSION_LESS "3.28"
      OR NOT DEFINED _cmake_import_check_xcframework_for_${_cmake_target}
      OR NOT IS_DIRECTORY "${_cmake_import_check_xcframework_for_${_cmake_target}}")
    foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
      if(NOT EXISTS "${_cmake_file}")
        message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
      endif()
    endforeach()
  endif()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
